import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Bot, Users, MessageCircle, Target, Star, TrendingUp } from "lucide-react";

const Features = () => {
  const features = [
    {
      icon: Bot,
      title: "AI-Powered Matching",
      description: "Our intelligent system matches entrepreneurs with the perfect mentors based on industry, skills, goals, and location.",
      highlight: "Smart matching algorithm"
    },
    {
      icon: MessageCircle,
      title: "Real-time Chat & Support",
      description: "Connect instantly with mentors through our integrated chat platform with AI-generated conversation starters.",
      highlight: "24/7 communication"
    },
    {
      icon: Target,
      title: "Actionable Guidance",
      description: "Receive personalized action points and next steps generated by AI after each mentoring session.",
      highlight: "Personalized roadmaps"
    },
    {
      icon: Users,
      title: "Expert Mentor Network",
      description: "Access to experienced entrepreneurs and industry experts who understand rural business challenges.",
      highlight: "500+ verified mentors"
    },
    {
      icon: TrendingUp,
      title: "Business Growth Tracking",
      description: "Monitor your progress with built-in analytics and milestone tracking to measure your business growth.",
      highlight: "Data-driven insights"
    },
    {
      icon: Star,
      title: "Quality Assurance",
      description: "All mentors are vetted and rated by the community to ensure you get high-quality guidance every time.",
      highlight: "Verified excellence"
    }
  ];

  return (
    <section id="features" className="py-20 bg-gradient-subtle">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 bg-sage-green/20 text-earth-brown px-4 py-2 rounded-full text-sm font-medium mb-6 border border-sage-green/30">
            <Star className="w-4 h-4" />
            Platform Features
          </div>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-foreground mb-6">
            Everything You Need to
            <span className="bg-gradient-primary bg-clip-text text-transparent"> Succeed</span>
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Our comprehensive platform provides all the tools, connections, and guidance rural entrepreneurs need to build thriving businesses.
          </p>
        </div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-16">
          {features.map((feature, index) => {
            const IconComponent = feature.icon;
            return (
              <Card key={index} className="group hover:shadow-card transition-smooth bg-gradient-card border-sage-green/30 hover:-translate-y-2">
                <CardHeader>
                  <div className="w-12 h-12 bg-gradient-primary rounded-lg flex items-center justify-center mb-4 group-hover:scale-110 transition-bounce">
                    <IconComponent className="w-6 h-6 text-white" />
                  </div>
                  <CardTitle className="text-xl text-foreground">{feature.title}</CardTitle>
                  <div className="text-sm text-warm-gold font-medium">{feature.highlight}</div>
                </CardHeader>
                <CardContent>
                  <CardDescription className="text-muted-foreground leading-relaxed">
                    {feature.description}
                  </CardDescription>
                </CardContent>
              </Card>
            );
          })}
        </div>

        {/* CTA Section */}
        <div className="text-center">
          <Button variant="hero" size="lg" className="group">
            Explore All Features
            <TrendingUp className="w-5 h-5 group-hover:translate-x-1 transition-smooth" />
          </Button>
        </div>
      </div>
    </section>
  );
};

export default Features;