import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowRight, UserPlus, Search, MessageCircle, Target, CheckCircle } from "lucide-react";

const HowItWorks = () => {
  const steps = [
    {
      step: 1,
      icon: UserPlus,
      title: "Create Your Profile",
      description: "Sign up and tell us about your business goals, industry, and what kind of guidance you're looking for.",
      color: "forest-green"
    },
    {
      step: 2,
      icon: Search,
      title: "AI-Powered Matching",
      description: "Our intelligent system analyzes your profile and matches you with the most suitable mentors in your area of interest.",
      color: "warm-gold"
    },
    {
      step: 3,
      icon: MessageCircle,
      title: "Connect & Chat",
      description: "Start conversations with your matched mentors using our chat platform with AI-generated conversation starters.",
      color: "sage-green"
    },
    {
      step: 4,
      icon: Target,
      title: "Receive Guidance",
      description: "Get personalized advice, resources, and actionable next steps generated by AI after each mentoring session.",
      color: "earth-brown"
    },
    {
      step: 5,
      icon: CheckCircle,
      title: "Achieve Success",
      description: "Track your progress, implement recommendations, and watch your rural business grow with expert guidance.",
      color: "forest-green"
    }
  ];

  return (
    <section id="how-it-works" className="py-20 bg-background">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 bg-sage-green/20 text-earth-brown px-4 py-2 rounded-full text-sm font-medium mb-6 border border-sage-green/30">
            <Target className="w-4 h-4" />
            Simple Process
          </div>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-foreground mb-6">
            Your Journey to
            <span className="bg-gradient-primary bg-clip-text text-transparent"> Success </span>
            in 5 Steps
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            We've designed a simple, intuitive process that connects you with the right mentors and helps you achieve your business goals efficiently.
          </p>
        </div>

        {/* Steps */}
        <div className="max-w-4xl mx-auto">
          {steps.map((step, index) => {
            const IconComponent = step.icon;
            const isLast = index === steps.length - 1;
            
            return (
              <div key={index} className="relative">
                {/* Step Card */}
                <div className="flex flex-col md:flex-row items-center gap-8 mb-12">
                  {/* Step Number & Icon */}
                  <div className="flex-shrink-0">
                    <div className="relative">
                      <div className={`w-20 h-20 bg-${step.color} rounded-full flex items-center justify-center shadow-card`}>
                        <IconComponent className="w-10 h-10 text-white" />
                      </div>
                      <div className="absolute -top-2 -right-2 w-8 h-8 bg-warm-gold text-white rounded-full flex items-center justify-center text-sm font-bold">
                        {step.step}
                      </div>
                    </div>
                  </div>

                  {/* Content */}
                  <Card className="flex-1 bg-gradient-card border-sage-green/30 hover:shadow-card transition-smooth">
                    <CardHeader>
                      <CardTitle className="text-xl text-foreground">{step.title}</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <CardDescription className="text-muted-foreground leading-relaxed text-base">
                        {step.description}
                      </CardDescription>
                    </CardContent>
                  </Card>
                </div>

                {/* Connector Line */}
                {!isLast && (
                  <div className="absolute left-10 top-20 w-0.5 h-12 bg-sage-green/30 hidden md:block" />
                )}
              </div>
            );
          })}
        </div>

        {/* CTA Section */}
        <div className="text-center mt-16">
          <h3 className="text-2xl font-bold text-foreground mb-4">
            Ready to Start Your Journey?
          </h3>
          <p className="text-muted-foreground mb-8 max-w-xl mx-auto">
            Join thousands of rural entrepreneurs who have already transformed their businesses with expert mentorship.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Button variant="hero" size="lg" className="group">
              Get Started Now
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-smooth" />
            </Button>
            <Button variant="outline" size="lg">
              Watch Demo Video
            </Button>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HowItWorks;